# Generated by Django 6.0.1 on 2026-02-09 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_board_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boardmember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('board',), name='unique_owner_per_board'),
        ),
    ]
